name: Update Markdown File

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  update_markdown:
    runs-on: ubuntu-latest
    permissions: 
      contents: write  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Generate markdown links
        run: python3 update_markdown.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/README.md problems/README.md
          git diff --staged --quiet || git commit -m "Auto-update file list in Markdown"
          git push