name: Update Markdown File

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  update_markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Generate markdown links
        run: python3 update_markdown.py

      - name: Commit and push changes
        run: |
          git add docs/README.md problems/README.md
          git commit -m "Auto-update file list in Markdown" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git